### ISSUE TITLE
add arthur mitchell to team

### ISSUE THREAD

**Issue by tierneytim** [spm/spm-python#15]
https://github.com/arthurmitchell96

Arthur would like to contribute to the team, 

Could I suggest,

1. Johan/peter add him as a contributor. IF you give me admin rights I am happy to do this as well
2. Yulia, ric, arthur and I run through install on his pc from scratch

**Comment by johmedr** [comment]
I think Arthur should be added to the SPM dev team, and gain the access through there (just so it’s easier to manage accesses). @pzeidman could you add him to the team?

**Comment by johmedr** [comment]
@tierneytim you are now an admin.

**Comment by tierneytim** [comment]
wonderful! job 1 done

**Comment by pzeidman** [comment]
Invitation sent to Arthur


________________________________

**Comment by tierneytim** [comment]
still need to finish job 2, will happen on wednesday

**Comment by arthurmitchell96** [comment]
I am added :)
